global using Button = System.Windows.Controls.Button;
global using Color = System.Drawing.Color;
global using ComboBox = System.Windows.Controls.ComboBox;
global using Complex = NAudio.Dsp.Complex;
global using ErrorCode = OpenTK.Windowing.GraphicsLibraryFramework.ErrorCode;
global using Key = System.Windows.Input.Key;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using Microsoft.Extensions.Logging;
global using MouseButton = System.Windows.Input.MouseButton;
global using MouseButtonEventArgs = System.Windows.Input.MouseButtonEventArgs;
global using MouseButtonState = System.Windows.Input.MouseButtonState;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using MouseWheelEventArgs = System.Windows.Input.MouseWheelEventArgs;
global using NAudio.CoreAudioApi;
global using NAudio.CoreAudioApi.Interfaces;
global using NAudio.Dsp;
global using NAudio.Wave;
global using Newtonsoft.Json;
global using OpenTK.Graphics.OpenGL4;
global using OpenTK.Mathematics;
global using OpenTK.Windowing.Common;
global using OpenTK.Windowing.Desktop;
global using OpenTK.Windowing.GraphicsLibraryFramework;
global using PixelFormat = OpenTK.Graphics.OpenGL4.PixelFormat;
global using Point = System.Windows.Point;
global using Serilog;
global using Serilog.Events;
global using Size = System.Windows.Size;
global using Slider = System.Windows.Controls.Slider;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Numerics;
global using System.Reactive.Disposables;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Threading.Channels;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Forms;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Threading;
global using UserControl = System.Windows.Forms.UserControl;
global using Vector = System.Numerics.Vector;
global using Vector2 = OpenTK.Mathematics.Vector2;
global using Vector3 = OpenTK.Mathematics.Vector3;
global using Vector4 = OpenTK.Mathematics.Vector4;
global using WindowState = System.Windows.WindowState;
global using WpfBrushes = System.Windows.Media.Brushes;
global using WpfColor = System.Windows.Media.Color;
global using WpfImage = System.Windows.Controls.Image;
global using GlfwWindow = OpenTK.Windowing.GraphicsLibraryFramework.Window;
global using Window = System.Windows.Window;
global using Application = System.Windows.Application;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;

global using OpenTK.Wpf;