global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Logging.Console;
global using NAudio.Dsp;
global using NAudio.Wave;
global using NAudio.CoreAudioApi;
global using NAudio.CoreAudioApi.Interfaces;
global using Newtonsoft.Json;
global using SkiaSharp;
global using SkiaSharp.Views.Desktop;
global using SkiaSharp.Views.WPF;
global using System.Collections.Concurrent;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Reactive.Disposables;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Threading.Channels;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Threading;
global using System.Numerics;
global using System.Buffers;
global using Vector = System.Numerics.Vector;
global using Complex = NAudio.Dsp.Complex;

// Add specific control aliases to resolve ambiguities
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using TextBox = System.Windows.Controls.TextBox;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using DpiChangedEventArgs = System.Windows.DpiChangedEventArgs;
global using RichTextBox = System.Windows.Controls.RichTextBox;