global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using NAudio.CoreAudioApi;
global using NAudio.CoreAudioApi.Interfaces;
global using NAudio.Dsp;
global using NAudio.Wave;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Serialization;
global using SkiaSharp;
global using SkiaSharp.Views.Desktop;
global using SkiaSharp.Views.WPF;
global using SpectrumNet.Controllers;
global using SpectrumNet.Controllers.AudioCore;
global using SpectrumNet.Controllers.Enums;
global using SpectrumNet.Controllers.Input;
global using SpectrumNet.Controllers.Interfaces;
global using SpectrumNet.Controllers.RenderCore;
global using SpectrumNet.Controllers.RenderCore.Overlay;
global using SpectrumNet.Controllers.SpectrumCore;
global using SpectrumNet.Controllers.UICore;
global using SpectrumNet.DataSettings;
global using SpectrumNet.DataSettings.Interfaces;
global using SpectrumNet.Service;
global using SpectrumNet.Service.Colors;
global using SpectrumNet.Service.ErrorHandlers;
global using SpectrumNet.Service.Utilities;
global using SpectrumNet.Views;
global using SpectrumNet.Views.Enums;
global using SpectrumNet.Views.Renderers;
global using SpectrumNet.Views.Utils;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Threading.Channels;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Threading;
global using static SkiaSharp.SKBlurStyle;
global using static SkiaSharp.SKPaintStyle;
global using static SpectrumNet.Controllers.SpectrumCore.Constants;
global using static SpectrumNet.Service.ErrorHandlers.SmartLogger;
global using static System.DateTime;
global using static System.Environment;
global using static System.FormattableString;
global using static System.GC;
global using static System.Math;
global using static System.Numerics.Vector;
global using static System.Runtime.CompilerServices.MethodImplOptions;
global using static System.TimeSpan;
global using static System.Windows.Input.Key;
global using static System.Windows.Media.VisualTreeHelper;
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using Complex = NAudio.Dsp.Complex;
global using DpiChangedEventArgs = System.Windows.DpiChangedEventArgs;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using LogLevel = SpectrumNet.Service.Enums.LogLevel;
global using MessageBox = System.Windows.MessageBox;
global using Parallel = System.Threading.Tasks.Parallel;
global using RichTextBox = System.Windows.Controls.RichTextBox;
global using TextBox = System.Windows.Controls.TextBox;


