namespace SpectrumNet.SN.Shared.Colors;

public static class Colors
{
    public static readonly IReadOnlyDictionary<string, SKColor> Definitions =
        new Dictionary<string, SKColor>(StringComparer.OrdinalIgnoreCase)
        {
            // Basic
            { "Solid", new(0xFF2196F3) }, { "Red", SKColors.Red }, { "Green", SKColors.Green },
            { "Blue", SKColors.Blue }, { "Yellow", SKColors.Yellow }, { "Orange", SKColors.Orange },
            { "Purple", SKColors.Purple }, { "Pink", SKColors.Pink }, { "Brown", SKColors.Brown },
            { "Gray", SKColors.Gray }, { "White", SKColors.White }, { "Black", SKColors.Black },

            // Red Shades
            { "DarkRed", SKColors.DarkRed }, { "LightCoral", SKColors.LightCoral },
            { "IndianRed", SKColors.IndianRed }, { "Firebrick", SKColors.Firebrick },
            { "Crimson", SKColors.Crimson }, { "Tomato", SKColors.Tomato },
            { "Salmon", SKColors.Salmon }, { "DarkSalmon", SKColors.DarkSalmon },
            { "Coral", SKColors.Coral }, { "LightSalmon", SKColors.LightSalmon },
            { "OrangeRed", SKColors.OrangeRed }, { "Maroon", SKColors.Maroon },
            { "BrickRed", new(0xFFCB4154) }, { "ChiliRed", new(0xFFE32636) },
            { "RoseRed", new(0xFFFF66CC) }, { "BloodRed", new(0xFF660000) },
            { "Cardinal", new(0xFFC41E3A) }, { "VenetianRed", new(0xFFC80815) },
            { "Cinnabar", new(0xFFE44D2E) }, { "RubyRed", new(0xFF9B111E) },
            { "CherryRed", new(0xFFDE3163) }, { "Lust", new(0xFFE62020) },
            { "Alizarin", new(0xFFE32636) },

            // Green Shades
            { "LimeGreen", SKColors.LimeGreen }, { "ForestGreen", SKColors.ForestGreen },
            { "SeaGreen", SKColors.SeaGreen }, { "SpringGreen", SKColors.SpringGreen },
            { "Olive", SKColors.Olive }, { "DarkOliveGreen", SKColors.DarkOliveGreen },
            { "MediumSeaGreen", SKColors.MediumSeaGreen }, { "DarkSeaGreen", SKColors.DarkSeaGreen },
            { "LightGreen", SKColors.LightGreen }, { "PaleGreen", SKColors.PaleGreen },
            { "MediumSpringGreen", SKColors.MediumSpringGreen }, { "YellowGreen", SKColors.YellowGreen },
            { "OliveDrab", SKColors.OliveDrab }, { "DarkGreen", SKColors.DarkGreen },
            { "Mint", new(0xFF3EB489) }, { "Jade", new(0xFF00A86B) },
            { "Pine", new(0xFF01796F) }, { "EmeraldGreen", new(0xFF009B77) },
            { "Lichen", new(0xFF8A9A5B) }, { "Asparagus", new(0xFF87A96B) },
            { "Avocado", new(0xFF568203) }, { "Fern", new(0xFF4F7942) },
            { "HunterGreen", new(0xFF355E3B) }, { "Mantis", new(0xFF74C365) },
            { "KellyGreen", new(0xFF4CBB17) }, { "Malachite", new(0xFF0BDA51) },
            { "Artichoke", new(0xFF8F9779) }, { "JuniperGreen", new(0xFF3A5F0B) },
            { "MossGreen", new(0xFF8A9A5B) }, { "Tea", new(0xFFD0F0C0) },
            { "Teal", new(0xFF008080) },

            // Blue Shades
            { "DodgerBlue", SKColors.DodgerBlue }, { "SteelBlue", SKColors.SteelBlue },
            { "RoyalBlue", SKColors.RoyalBlue }, { "MediumBlue", SKColors.MediumBlue },
            { "DeepSkyBlue", SKColors.DeepSkyBlue }, { "Navy", SKColors.Navy },
            { "SkyBlue", SKColors.SkyBlue }, { "LightSkyBlue", SKColors.LightSkyBlue },
            { "LightBlue", SKColors.LightBlue }, { "PowderBlue", SKColors.PowderBlue },
            { "CadetBlue", SKColors.CadetBlue }, { "CornflowerBlue", SKColors.CornflowerBlue },
            { "DarkBlue", SKColors.DarkBlue }, { "MidnightBlue", SKColors.MidnightBlue },
            { "SlateBlue", SKColors.SlateBlue }, { "MediumSlateBlue", SKColors.MediumSlateBlue },
            { "LightSlateBlue", new(0xFF8470FF) }, { "DarkSlateBlue", SKColors.DarkSlateBlue },
            { "OceanBlue", new(0xFF4F42B5) }, { "Denim", new(0xFF1560BD) },
            { "Glacier", new(0xFF80B1D3) }, { "Periwinkle", new(0xFFCCCCFF) },
            { "Aegean", new(0xFF5D8AA8) }, { "Aquamarine", new(0xFF7FFFD4) },
            { "AirForceBlue", new(0xFF5D8AA8) }, { "BabyBlue", new(0xFF89CFF0) },
            { "BerkeleyBlue", new(0xFF003262) }, { "Blueberry", new(0xFF4F86F7) },
            { "Byzantine", new(0xFF5D3954) }, { "Cerulean", new(0xFF007BA7) },
            { "Cobalt", new(0xFF0047AB) }, { "ColumbiaBlue", new(0xFFB9D9EB) },
            { "Cyan", SKColors.Cyan }, { "DuckBlue", new(0xFF006287) },
            { "FrenchBlue", new(0xFF0072BB) }, { "Glaucous", new(0xFF6082B6) },
            { "Honolulu", new(0xFF006DB0) }, { "Indigo", SKColors.Indigo },
            { "Iris", new(0xFF5A4FCF) }, { "Liberty", new(0xFF545AA7) },
            { "Majorelle", new(0xFF6050DC) }, { "Maya", new(0xFF73C2FB) },
            { "Maastricht", new(0xFF1C2841) }, { "Moonstone", new(0xFF3AA8C1) },
            { "NeonBlueVibrant", new(0xFF1A1CF6) }, { "Oxford", new(0xFF002147) },
            { "PersianBlue", new(0xFF1C39BB) }, { "PrussianBlue", new(0xFF003153) },
            { "Savoy", new(0xFF4B61D1) }, { "Ultramarine", new(0xFF120A8F) },
            { "Zaffre", new(0xFF0014A8) },

            // Purple Shades
            { "DarkOrchid", SKColors.DarkOrchid }, { "MediumPurple", SKColors.MediumPurple },
            { "BlueViolet", SKColors.BlueViolet }, { "DarkMagenta", SKColors.DarkMagenta },
            { "Violet", SKColors.Violet }, { "Plum", SKColors.Plum },
            { "Thistle", SKColors.Thistle }, { "Orchid", SKColors.Orchid },
            { "MediumOrchid", SKColors.MediumOrchid }, { "DarkViolet", SKColors.DarkViolet },
            { "RebeccaPurple", new(0xFF663399) }, { "LavenderPurple", new(0xFF967BB6) },
            { "Grape", new(0xFF6F2DA8) }, { "Mulberry", new(0xFFC54B8C) },
            { "Wisteria", new(0xFF997A8D) }, { "Amethyst", new(0xFF9966CC) },
            { "ByzantinePurple", new(0xFFBD33A4) }, { "Byzantium", new(0xFF702963) },
            { "Eggplant", new(0xFF614051) }, { "Fandango", new(0xFFB53389) },
            { "Finn", new(0xFF683068) }, { "Flirt", new(0xFFA2006D) },
            { "Fuchsia", SKColors.Fuchsia }, { "Heliotrope", new(0xFFDF73FF) },
            { "Hibiscus", new(0xFFB86391) }, { "Jazzberry", new(0xFFA50B5E) },
            { "Lavender", SKColors.Lavender }, { "Lilac", new(0xFFC8A2C8) },
            { "Magenta", SKColors.Magenta }, { "Mauve", new(0xFFE0B0FF) },
            { "MediumPurpleSK", new(0xFF9370DB) }, { "Mountbatten", new(0xFF997A8D) },
            { "Pomp", new(0xFF7B4259) }, { "Phlox", new(0xFFDF00FF) },
            { "Purpureus", new(0xFF9A4EAE) }, { "RoyalPurpleSK", new(0xFF7851A9) },
            { "Tyrian", new(0xFF66023C) }, { "VioletEggplant", new(0xFF991199) },

            // Yellow/Orange
            { "Gold", SKColors.Gold }, { "DarkOrange", SKColors.DarkOrange },
            { "Goldenrod", SKColors.Goldenrod }, { "DarkGoldenrod", SKColors.DarkGoldenrod },
            { "LightGoldenrodYellow", SKColors.LightGoldenrodYellow },
            { "PaleGoldenrod", SKColors.PaleGoldenrod },
            { "Khaki", SKColors.Khaki }, { "DarkKhaki", SKColors.DarkKhaki },
            { "LemonChiffon", SKColors.LemonChiffon }, { "LightYellow", SKColors.LightYellow },
            { "PapayaWhip", SKColors.PapayaWhip }, { "Moccasin", SKColors.Moccasin },
            { "PeachPuff", SKColors.PeachPuff }, { "Butter", new(0xFFFFE135) },
            { "Canary", new(0xFFFFFF99) }, { "Apricot", new(0xFFFBCEB1) },
            { "Mandarin", new(0xFFF37A48) }, { "Honey", new(0xFFA66F00) },
            { "Amber", new(0xFFFFBF00) }, { "Aureolin", new(0xFFFDEE00) },
            { "BananaMania", new(0xFFFAE7B5) }, { "Beer", new(0xFFFC913A) },
            { "Buff", new(0xFFF0DC82) }, { "Butterscotch", new(0xFFFC9D03) },
            { "Caramel", new(0xFFFFD59A) }, { "Champagne", new(0xFFF7E7CE) },
            { "Corn", new(0xFFFBEC5D) }, { "Cream", new(0xFFFFFFCC) },
            { "Dandelion", new(0xFFF0E130) }, { "GoldenYellow", new(0xFFFFDF00) },
            { "Jasmine", new(0xFFF8DE7E) }, { "Lemon", new(0xFFFFF700) },
            { "Maize", new(0xFFE4B018) }, { "Mustard", new(0xFFE1AD01) },
            { "Rajah", new(0xFFFBAB60) }, { "Saffron", new(0xFFF4C430) },
            { "Sunglow", new(0xFFFFCC33) }, { "Sunset", new(0xFFFAD6A5) },
            { "TigersEye", new(0xFFE08D3C) }, { "Urobilin", new(0xFFE1C43F) },
            { "Bronze", new(0xFFCD7F32) }, { "BurntOrange", new(0xFFCC5500) },
            { "Cider", new(0xFFF78700) }, { "Copper", new(0xFFB87333) },
            { "InternationalOrange", new(0xFFFF4F00) }, { "Persimmon", new(0xFFCC6500) },
            { "PrincetonOrange", new(0xFFF58025) }, { "Pumpkin", new(0xFFFF7518) },
            { "TangoPink", new(0xFFE4717A) }, { "TerraCotta", new(0xFFE2725B) },
            { "Vermilion", new(0xFFFF4000) },

            // Brown
            { "SandyBrown", SKColors.SandyBrown }, { "RosyBrown", SKColors.RosyBrown },
            { "SaddleBrown", SKColors.SaddleBrown }, { "Chocolate", SKColors.Chocolate },
            { "Peru", SKColors.Peru }, { "Sienna", SKColors.Sienna },
            { "BurlyWood", SKColors.BurlyWood }, { "Tan", SKColors.Tan },
            { "Wheat", SKColors.Wheat }, { "NavajoWhite", SKColors.NavajoWhite },
            { "Bisque", SKColors.Bisque }, { "BlanchedAlmond", SKColors.BlanchedAlmond },
            { "Cornsilk", SKColors.Cornsilk }, { "Mocha", new(0xFF967117) },
            { "Cinnamon", new(0xFFD2691E) }, { "Taupe", new(0xFF483C32) },
            { "Umber", new(0xFF635147) }, { "Auburn", new(0xFF922724) },
            { "Beaver", new(0xFF9F8170) }, { "Beige", SKColors.Beige },
            { "Bole", new(0xFF79443B) }, { "BuffBrown", new(0xFFE0AB76) },
            { "BurntUmbra", new(0xFF8A3324) }, { "Cafe", new(0xFF4B3621) },
            { "Camel", new(0xFFC19A6B) }, { "Chamoisee", new(0xFF9A784F) },
            { "Chestnut", new(0xFF954535) }, { "CoffeeBrown", new(0xFF4A2C2A) },
            { "CoralBrown", new(0xFF5B3A29) }, { "Cordovan", new(0xFF893F45) },
            { "Cork", new(0xFF583539) }, { "Desert", new(0xFFEDC9AF) },
            { "Dun", new(0xFFC19A6B) }, { "Ecru", new(0xFFC2B280) },
            { "Fallow", new(0xFFC19A6B) }, { "Fawn", new(0xFFE5AA70) },
            { "KhakiBrown", new(0xFFC3B091) }, { "Lion", new(0xFFC19A6B) },
            { "Liver", new(0xFF674C47) }, { "Mahogany", new(0xFFC04000) },
            { "Ochre", new(0xFFCC7722) }, { "Russet", new(0xFF8D4E85) },
            { "RustBrown", new(0xFFB7410E) }, { "Sand", new(0xFFC2B280) },
            { "Sinopia", new(0xFFCB410B) }, { "Walnut", new(0xFF773F1A) },
            { "Wood", new(0xFF823A09) },

            // Pink
            { "PaleVioletRed", SKColors.PaleVioletRed }, { "HotPink", SKColors.HotPink },
            { "DeepPink", SKColors.DeepPink }, { "LightPink", SKColors.LightPink },
            { "MistyRose", SKColors.MistyRose }, { "LavenderBlush", SKColors.LavenderBlush },
            { "Bubblegum", new(0xFFFFC1CC) }, { "Flamingo", new(0xFFFC8EAC) },
            { "Blush", new(0xFFDE5D83) }, { "CherryBlossom", new(0xFFFFB7C5) },
            { "Amaranth", new(0xFFE52B50) }, { "Baker", new(0xFFFF5F65) },
            { "Begonia", new(0xFFFB607F) }, { "Brink", new(0xFFFB607F) },
            { "BrinkPink", new(0xFFD88CA6) }, { "Carnation", new(0xFFFFA6C9) },
            { "Cerise", new(0xFFDE3163) }, { "Charm", new(0xFFE68FAC) },
            { "ChineseViolet", new(0xFF856088) }, { "CoralPink", new(0xFFFF7F50) },
            { "Cyclamen", new(0xFFF4BBD3) }, { "FrenchPink", new(0xFFFD6C9E) },
            { "LavenderPink", new(0xFFB57EDC) }, { "MexicanPink", new(0xFFE4007C) },
            { "MountainPink", new(0xFFD58E94) }, { "MulberryPink", new(0xFFC8509B) },
            { "PaleChestnut", new(0xFFDDACBF) }, { "PearlPink", new(0xFFEA8BA0) },
            { "PersianPink", new(0xFFF77FBE) }, { "PersianRose", new(0xFFFE28A2) },
            { "PiggyPink", new(0xFFFDDDE6) }, { "PinkLace", new(0xFFFFDDF4) },
            { "PinkLavender", new(0xFFD8B2D1) }, { "PinkPearl", new(0xFFE7ACCF) },
            { "RosyPink", new(0xFFFF66CC) }, { "Rosewood", new(0xFF65000B) },
            { "RubineRed", new(0xFFD10056) }, { "TeaRose", new(0xFFF4C2C2) },
            { "ThulianPink", new(0xFFDE6FA1) },

            // Gray
            { "Silver", SKColors.Silver }, { "DimGray", SKColors.DimGray },
            { "LightSlateGray", SKColors.LightSlateGray },
            { "DarkSlateGray", SKColors.DarkSlateGray },
            { "Gainsboro", SKColors.Gainsboro }, { "LightGray", SKColors.LightGray },
            { "DarkGray", SKColors.DarkGray }, { "SlateGray", SKColors.SlateGray },
            { "LightSteelBlue", SKColors.LightSteelBlue }, { "Ash", new(0xFFB2BEB5) },
            { "Pewter", new(0xFF96A8A1) }, { "Smoke", new(0xFF738276) },
            { "Granite", new(0xFF676767) }, { "AshGray", new(0xFFB2BEB5) },
            { "BattleshipGray", new(0xFF848482) }, { "Cadet", new(0xFF91A3B0) },
            { "Charcoal", new(0xFF36454F) }, { "Cinerous", new(0xFF98817B) },
            { "Davy", new(0xFF555555) }, { "Ebony", new(0xFF555D50) },
            { "GlaucousGray", new(0xFF6082B6) }, { "Gunmetal", new(0xFF2A3439) },
            { "Jet", new(0xFF343434) }, { "Onyx", new(0xFF0F0F0F) },
            { "Oyster", new(0xFFE6D5D1) }, { "Payne", new(0xFF536878) },
            { "Platinum", new(0xFFE5E4E2) }, { "Rocket", new(0xFF8A7F8D) },
            { "Slate", new(0xFF708090) }, { "Stone", new(0xFF928E85) },
            { "Timberwolf", new(0xFFDBD7D2) },

            // Special
            { "Ivory", SKColors.Ivory }, { "MintCream", SKColors.MintCream },
            { "Azure", SKColors.Azure }, { "AliceBlue", SKColors.AliceBlue },
            { "AntiqueWhite", SKColors.AntiqueWhite }, { "Aqua", SKColors.Aqua },
            { "Chartreuse", SKColors.Chartreuse }, { "DarkCyan", SKColors.DarkCyan },
            { "FloralWhite", SKColors.FloralWhite }, { "GhostWhite", SKColors.GhostWhite },
            { "Honeydew", SKColors.Honeydew }, { "Linen", SKColors.Linen },
            { "MediumAquamarine", SKColors.MediumAquamarine },
            { "MediumTurquoise", SKColors.MediumTurquoise },
            { "OldLace", SKColors.OldLace }, { "PaleTurquoise", SKColors.PaleTurquoise },
            { "Snow", SKColors.Snow }, { "Turquoise", SKColors.Turquoise },
            { "WhiteSmoke", SKColors.WhiteSmoke }, { "CopperMetallic", new(0xFFB87333) },
            { "Brass", new(0xFFB5A642) }, { "Steel", new(0xFF4682B4) },
            { "AntiqueBrass", new(0xFFCD9575) }, { "BronzeMetallic", new(0xFF8C7853) },
            { "ChromeGold", new(0xFFFFCF40) }, { "ChromeSilver", new(0xFFDDDDDD) },
            { "CopperRed", new(0xFFCB6D51) }, { "GoldMetallic", new(0xFFD4AF37) },
            { "Mercury", new(0xFFE6E6E6) }, { "MetallicGold", new(0xFFD5A03C) },
            { "MetallicSunburst", new(0xFF9C7C38) }, { "MetallicSunrise", new(0xFF817A70) },
            { "OldGold", new(0xFFCFB53B) }, { "RoseGold", new(0xFFB76E79) },
            { "SilverMetallic", new(0xFFC0C0C0) }, { "TitaniumGold", new(0xFFEEA319) },
            { "TitaniumWhite", new(0xFFF5F5F5) }, { "LightPurple", new(0xFFDDA0DD) },
            { "Emerald", new(0xFF50C878) }, { "Ruby", new(0xFFE0115F) },
            { "Sapphire", new(0xFF0F52BA) }, { "JetBlack", new(0xFF0A0A0A) },
            { "Opal", new(0xFFA8C3BC) }, { "Garnet", new(0xFF733635) },
            { "TurquoiseBlue", new(0xFF00CED1) }, { "Sepia", new(0xFF704214) },
            { "Tangerine", new(0xFFF28500) }, { "Verdant", new(0xFF4CAF50) },
            { "Scarlet", new(0xFFFF2400) }, { "ElectricBlue", new(0xFF7DF9FF) },
            { "IceBlue", new(0xFF99FFFF) }, { "MagentaPink", new(0xFFCC338B) },
            { "PeacockBlue", new(0xFF33A1C9) }, { "PumpkinCustom", new(0xFFFF7518) },
            { "Seafoam", new(0xFF93E9BE) }, { "Sunflower", new(0xFFFFDA03) },
            { "TealBlue", new(0xFF367588) }, { "UltramarineBlue", new(0xFF3F00FF) },
            { "VermilionCustom", new(0xFFE34234) }, { "Wine", new(0xFF722F37) },
            { "Zomp", new(0xFF39A78E) }, { "Celadon", new(0xFFACE1AF) },
            { "DustyRose", new(0xFFDCAE96) }, { "FawnBrown", new(0xFFE5AA70) },
            { "IndigoBlue", new(0xFF4B0082) }, { "Lapis", new(0xFF26619C) },
            { "Raven", new(0xFF757575) }, { "SageGreen", new(0xFF9BAA8D) },
            { "Twilight", new(0xFF4A4066) },

            // Gems
            { "Alexandrite", new(0xFF7FFFD4) }, { "Amazonite", new(0xFF00DFBB) },
            { "Aventurine", new(0xFF84C3BE) }, { "Beryl", new(0xFFDAA520) },
            { "Bloodstone", new(0xFF800020) }, { "Calcite", new(0xFFE9E5CE) },
            { "Carnelian", new(0xFFB31B1B) }, { "Citrine", new(0xFFE4D00A) },
            { "Diamond", new(0xFFB9F2FF) }, { "Fluorite", new(0xFF7A89B8) },
            { "Iolite", new(0xFF3A3A78) }, { "JadeGem", new(0xFF00A36C) },
            { "Jasper", new(0xFFD73B3E) }, { "Kunzite", new(0xFFD47FFF) },
            { "Kyanite", new(0xFF5E91D4) }, { "Labradorite", new(0xFF7B8282) },
            { "Morganite", new(0xFFCCCCFF) }, { "Obsidian", new(0xFF000000) },
            { "Peridot", new(0xFF9BC256) }, { "Quartz", new(0xFFEDEAE0) },
            { "Rhodonite", new(0xFFE73895) }, { "RoseQuartz", new(0xFFFF91A4) },
            { "Sphene", new(0xFFC3B091) }, { "Spinel", new(0xFFFF5A5F) },
            { "Sunstone", new(0xFFDD985C) }, { "Tiger", new(0xFFE08D3C) },
            { "Tanzanite", new(0xFF4D5A9E) }, { "TopazGem", new(0xFFFFC87C) },
            { "Tourmaline", new(0xFF85461E) }, { "TurquoiseGem", new(0xFF30D5C8) },
            { "Zircon", new(0xFFADE6C4) },

            // Neon
            { "NeonBlue", new(0xFF4D4DFF) }, { "NeonGreen", new(0xFF39FF14) },
            { "NeonOrange", new(0xFFFF5F1F) }, { "NeonPink", new(0xFFFF44CC) },
            { "NeonPurple", new(0xFFBF00FF) }, { "NeonRed", new(0xFFFF3131) },
            { "NeonYellow", new(0xFFFFFF00) }, { "AcidGreen", new(0xFFB0BF1A) },
            { "ElectricIndigo", new(0xFF6F00FF) }, { "ElectricLime", new(0xFFCCFF00) },
            { "ElectricPurple", new(0xFFBF00FF) }, { "ElectricViolet", new(0xFF8F00FF) },
            { "FluorescentOrange", new(0xFFFFBF00) }, { "FluorescentPink", new(0xFFFF1493) },
            { "FluorescentYellow", new(0xFFCCFF00) }, { "LaserLemon", new(0xFFFEFE22) },
            { "PsychedelicPurple", new(0xFFDF00FF) }, { "ShockingPink", new(0xFFFC0FC0) },
            { "UltraViolet", new(0xFF5F00BA) },

            // Pastel
            { "PastelBlue", new(0xFFAEC6CF) }, { "PastelBrown", new(0xFF836953) },
            { "PastelGray", new(0xFFCFCFC4) }, { "PastelGreen", new(0xFF77DD77) },
            { "PastelMagenta", new(0xFFF49AC2) }, { "PastelOrange", new(0xFFFFB347) },
            { "PastelPink", new(0xFFDEA5A4) }, { "PastelPurple", new(0xFFB39EB5) },
            { "PastelRed", new(0xFFFF6961) }, { "PastelViolet", new(0xFFCB99C9) },
            { "PastelYellow", new(0xFFFFFF9E) }, { "BabyPink", new(0xFFF4C2C2) },
            { "ButtermilkYellow", new(0xFFF3F4C0) }, { "CelestialBlue", new(0xFF4997D0) },
            { "DuckyYellow", new(0xFFFFDB58) }, { "FreshGreen", new(0xFFB5D8CC) },
            { "MellowApricot", new(0xFFF8B878) }, { "MintGreen", new(0xFF98FB98) },
            { "PastelRosyPink", new(0xFFFF66CC) }, { "SalmonPink", new(0xFFFF91A4) },
            { "SandyBeige", new(0xFFF5DEB3) }, { "SeafoamGreen", new(0xFF71EEB8) },
            { "SoftLilac", new(0xFFE6CFE6) }
        };
}
