global using NAudio.CoreAudioApi;
global using NAudio.CoreAudioApi.Interfaces;
global using NAudio.Dsp;
global using NAudio.Wave;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Converters;
global using Newtonsoft.Json.Serialization;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using SkiaSharp;
global using SkiaSharp.Views.Desktop;
global using SkiaSharp.Views.WPF;
global using SpectrumNet.SN.Controllers;
global using SpectrumNet.SN.Controllers.Input;
global using SpectrumNet.SN.Controllers.Input.Interfaces;
global using SpectrumNet.SN.Controllers.Interfaces;
global using SpectrumNet.SN.Controllers.View;
global using SpectrumNet.SN.Controllers.View.Interfaces;
global using SpectrumNet.SN.Settings;
global using SpectrumNet.SN.Settings.Base;
global using SpectrumNet.SN.Settings.Constants;
global using SpectrumNet.SN.Settings.Interfaces;
global using SpectrumNet.SN.Settings.Models;
global using SpectrumNet.SN.Shared.Colors;
global using SpectrumNet.SN.Shared.Colors.Interfaces;
global using SpectrumNet.SN.Shared.Controls;
global using SpectrumNet.SN.Shared.Converters;
global using SpectrumNet.SN.Shared.Enums;
global using SpectrumNet.SN.Shared.Logging;
global using SpectrumNet.SN.Shared.Utils;
global using SpectrumNet.SN.Sound;
global using SpectrumNet.SN.Sound.Interfaces;
global using SpectrumNet.SN.Spectrum;
global using SpectrumNet.SN.Spectrum.Core;
global using SpectrumNet.SN.Spectrum.Interfaces;
global using SpectrumNet.SN.Spectrum.Models;
global using SpectrumNet.SN.Spectrum.Utils.Math;
global using SpectrumNet.SN.Themes;
global using SpectrumNet.SN.Themes.Interfaces;
global using SpectrumNet.SN.Visualization.Abstract.Core;
global using SpectrumNet.SN.Visualization.Abstract.Helpers;
global using SpectrumNet.SN.Visualization.Abstract.Helpers.Interfaces;
global using SpectrumNet.SN.Visualization.Abstract.Processing;
global using SpectrumNet.SN.Visualization.Abstract.Rendering;
global using SpectrumNet.SN.Visualization.Core;
global using SpectrumNet.SN.Visualization.Interfaces;
global using SpectrumNet.SN.Visualization.Overlay.Core;
global using SpectrumNet.SN.Visualization.Overlay.Interfaces;
global using SpectrumNet.SN.Visualization.Overlay.Managers;
global using SpectrumNet.SN.Visualization.Overlay.Native;
global using SpectrumNet.SN.Visualization.Performance;
global using SpectrumNet.SN.Visualization.Performance.Interfaces;
global using SpectrumNet.SN.Visualization.Renderers;
global using SpectrumNet.SN.Visualization.Utils;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Threading.Channels;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Navigation;
global using System.Windows.Threading;
global using static Serilog.Log;
global using static SkiaSharp.SKPaintStyle;
global using static SpectrumNet.SN.Shared.Logging.SmartLogger;
global using static SpectrumNet.SN.Spectrum.Utils.Constants;
global using static System.DateTime;
global using static System.Environment;
global using static System.GC;
global using static System.Math;
global using static System.Numerics.Vector;
global using static System.Runtime.CompilerServices.MethodImplOptions;
global using static System.TimeSpan;
global using static System.Windows.Media.VisualTreeHelper;
global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using Color = System.Windows.Media.Color;
global using ComboBox = System.Windows.Controls.ComboBox;
global using Complex = NAudio.Dsp.Complex;
global using DpiChangedEventArgs = System.Windows.DpiChangedEventArgs;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using KeyEventHandler = System.Windows.Input.KeyEventHandler;
global using LogLevel = SpectrumNet.SN.Shared.Enums.LogLevel;
global using MessageBox = System.Windows.MessageBox;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using Parallel = System.Threading.Tasks.Parallel;
global using Settings = SpectrumNet.SN.Settings.Settings;
global using TextBox = System.Windows.Controls.TextBox;
global using UserControl = System.Windows.Controls.UserControl;

global using SpectrumNet.SN.Visualization.Abstract.Rendering.Interfaces;
global using SpectrumNet.SN.Visualization.Abstract.Processing.Interfaces;