global using System.Collections.Concurrent;
global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Numerics;
global using System.Reactive.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Threading.Channels;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Navigation;
global using System.Windows.Threading;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using NAudio.CoreAudioApi;
global using NAudio.CoreAudioApi.Interfaces;
global using NAudio.Wave;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Converters;
global using Newtonsoft.Json.Linq;
global using Polly;
global using Polly.Retry;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using SkiaSharp;
global using SkiaSharp.Views.Desktop;
global using SkiaSharp.Views.WPF;
global using SpectrumNet.SN.Controllers;
global using SpectrumNet.SN.Settings;
global using SpectrumNet.SN.Shared.Colors;
global using SpectrumNet.SN.Shared.Converters;
global using SpectrumNet.SN.Shared.Enums;
global using SpectrumNet.SN.Shared.Logging;
global using SpectrumNet.SN.Sound;
global using SpectrumNet.SN.Spectrum;
global using SpectrumNet.SN.Themes;
global using SpectrumNet.SN.Visualization;
global using SpectrumNet.SN.Visualization.Overlay;
global using SpectrumNet.SN.Visualization.Renderers;
global using static System.DateTime;
global using static System.Environment;
global using static System.GC;
global using static System.Math;
global using static System.Numerics.Vector;
global using static System.TimeSpan;
global using static Serilog.Log;
global using static SkiaSharp.SKPaintStyle;
global using static SpectrumNet.SN.Shared.Logging.SmartLogger;
global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using Color = System.Windows.Media.Color;
global using ComboBox = System.Windows.Controls.ComboBox;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using LogLevel = SpectrumNet.SN.Shared.Enums.LogLevel;
global using MessageBox = System.Windows.MessageBox;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using TextBox = System.Windows.Controls.TextBox;
