#nullable enable

namespace SpectrumNet.Service.Colors;

public static class Colors
{
    public static readonly IReadOnlyDictionary<string, SKColor> ColorDefinitions =
        new Dictionary<string, SKColor>(StringComparer.OrdinalIgnoreCase)
        {
            // Basic colors
            { "Solid", new SKColor(0xFF2196F3) },
            { "Red", SKColors.Red },
            { "Green", SKColors.Green },
            { "Blue", SKColors.Blue },
            { "Yellow", SKColors.Yellow },
            { "Orange", SKColors.Orange },
            { "Purple", SKColors.Purple },
            { "Pink", SKColors.Pink },
            { "Brown", SKColors.Brown },
            { "Gray", SKColors.Gray },
            { "White", SKColors.White },
            { "Black", SKColors.Black },

            // Shades of red
            { "DarkRed", SKColors.DarkRed },
            { "LightCoral", SKColors.LightCoral },
            { "IndianRed", SKColors.IndianRed },
            { "Firebrick", SKColors.Firebrick },
            { "Crimson", SKColors.Crimson },
            { "Tomato", SKColors.Tomato },
            { "Salmon", SKColors.Salmon },
            { "DarkSalmon", SKColors.DarkSalmon },
            { "Coral", SKColors.Coral },
            { "LightSalmon", SKColors.LightSalmon },
            { "OrangeRed", SKColors.OrangeRed },
            { "Maroon", SKColors.Maroon },
            { "BrickRed", new SKColor(0xFFCB4154) },
            { "ChiliRed", new SKColor(0xFFE32636) },
            { "RoseRed", new SKColor(0xFFFF66CC) },
            { "BloodRed", new SKColor(0xFF660000) },
            { "Cardinal", new SKColor(0xFFC41E3A) },
            { "VenetianRed", new SKColor(0xFFC80815) },
            { "Cinnabar", new SKColor(0xFFE44D2E) },
            { "RubyRed", new SKColor(0xFF9B111E) },
            { "CherryRed", new SKColor(0xFFDE3163) },
            { "Lust", new SKColor(0xFFE62020) },
            { "Alizarin", new SKColor(0xFFE32636) },

            // Shades of green
            { "LimeGreen", SKColors.LimeGreen },
            { "ForestGreen", SKColors.ForestGreen },
            { "SeaGreen", SKColors.SeaGreen },
            { "SpringGreen", SKColors.SpringGreen },
            { "Olive", SKColors.Olive },
            { "DarkOliveGreen", SKColors.DarkOliveGreen },
            { "MediumSeaGreen", SKColors.MediumSeaGreen },
            { "DarkSeaGreen", SKColors.DarkSeaGreen },
            { "LightGreen", SKColors.LightGreen },
            { "PaleGreen", SKColors.PaleGreen },
            { "MediumSpringGreen", SKColors.MediumSpringGreen },
            { "YellowGreen", SKColors.YellowGreen },
            { "OliveDrab", SKColors.OliveDrab },
            { "DarkGreen", SKColors.DarkGreen },
            { "Mint", new SKColor(0xFF3EB489) },
            { "Jade", new SKColor(0xFF00A86B) },
            { "Pine", new SKColor(0xFF01796F) },
            { "EmeraldGreen", new SKColor(0xFF009B77) },
            { "Lichen", new SKColor(0xFF8A9A5B) },
            { "Asparagus", new SKColor(0xFF87A96B) },
            { "Avocado", new SKColor(0xFF568203) },
            { "Fern", new SKColor(0xFF4F7942) },
            { "HunterGreen", new SKColor(0xFF355E3B) },
            { "Mantis", new SKColor(0xFF74C365) },
            { "KellyGreen", new SKColor(0xFF4CBB17) },
            { "Malachite", new SKColor(0xFF0BDA51) },
            { "Artichoke", new SKColor(0xFF8F9779) },
            { "JuniperGreen", new SKColor(0xFF3A5F0B) },
            { "MossGreen", new SKColor(0xFF8A9A5B) },
            { "Tea", new SKColor(0xFFD0F0C0) },
            { "Teal", new SKColor(0xFF008080) },

            // Shades of blue
            { "DodgerBlue", SKColors.DodgerBlue },
            { "SteelBlue", SKColors.SteelBlue },
            { "RoyalBlue", SKColors.RoyalBlue },
            { "MediumBlue", SKColors.MediumBlue },
            { "DeepSkyBlue", SKColors.DeepSkyBlue },
            { "Navy", SKColors.Navy },
            { "SkyBlue", SKColors.SkyBlue },
            { "LightSkyBlue", SKColors.LightSkyBlue },
            { "LightBlue", SKColors.LightBlue },
            { "PowderBlue", SKColors.PowderBlue },
            { "CadetBlue", SKColors.CadetBlue },
            { "CornflowerBlue", SKColors.CornflowerBlue },
            { "DarkBlue", SKColors.DarkBlue },
            { "MidnightBlue", SKColors.MidnightBlue },
            { "SlateBlue", SKColors.SlateBlue },
            { "MediumSlateBlue", SKColors.MediumSlateBlue },
            { "LightSlateBlue", new SKColor(0xFF8470FF) },
            { "DarkSlateBlue", SKColors.DarkSlateBlue },
            { "OceanBlue", new SKColor(0xFF4F42B5) },
            { "Denim", new SKColor(0xFF1560BD) },
            { "Glacier", new SKColor(0xFF80B1D3) },
            { "Periwinkle", new SKColor(0xFFCCCCFF) },
            { "Aegean", new SKColor(0xFF5D8AA8) },
            { "Aquamarine", new SKColor(0xFF7FFFD4) },
            { "AirForceBlue", new SKColor(0xFF5D8AA8) },
            { "BabyBlue", new SKColor(0xFF89CFF0) },
            { "BerkeleyBlue", new SKColor(0xFF003262) },
            { "Blueberry", new SKColor(0xFF4F86F7) },
            { "Byzantine", new SKColor(0xFF5D3954) },
            { "Cerulean", new SKColor(0xFF007BA7) },
            { "Cobalt", new SKColor(0xFF0047AB) },
            { "ColumbiaBlue", new SKColor(0xFFB9D9EB) },
            { "Cyan", SKColors.Cyan },
            { "DuckBlue", new SKColor(0xFF006287) },
            { "FrenchBlue", new SKColor(0xFF0072BB) },
            { "Glaucous", new SKColor(0xFF6082B6) },
            { "Honolulu", new SKColor(0xFF006DB0) },
            { "Indigo", SKColors.Indigo },
            { "Iris", new SKColor(0xFF5A4FCF) },
            { "Liberty", new SKColor(0xFF545AA7) },
            { "Majorelle", new SKColor(0xFF6050DC) },
            { "Maya", new SKColor(0xFF73C2FB) },
            { "Maastricht", new SKColor(0xFF1C2841) },
            { "Moonstone", new SKColor(0xFF3AA8C1) },
            { "NeonBlueVibrant", new SKColor(0xFF1A1CF6) },
            { "Oxford", new SKColor(0xFF002147) },
            { "PersianBlue", new SKColor(0xFF1C39BB) },
            { "PrussianBlue", new SKColor(0xFF003153) },
            { "Savoy", new SKColor(0xFF4B61D1) },
            { "Ultramarine", new SKColor(0xFF120A8F) },
            { "Zaffre", new SKColor(0xFF0014A8) },

            // Shades of purple
            { "DarkOrchid", SKColors.DarkOrchid },
            { "MediumPurple", SKColors.MediumPurple },
            { "BlueViolet", SKColors.BlueViolet },
            { "DarkMagenta", SKColors.DarkMagenta },
            { "Violet", SKColors.Violet },
            { "Plum", SKColors.Plum },
            { "Thistle", SKColors.Thistle },
            { "Orchid", SKColors.Orchid },
            { "MediumOrchid", SKColors.MediumOrchid },
            { "DarkViolet", SKColors.DarkViolet },
            { "RebeccaPurple", new SKColor(0xFF663399) },
            { "LavenderPurple", new SKColor(0xFF967BB6) },
            { "Grape", new SKColor(0xFF6F2DA8) },
            { "Mulberry", new SKColor(0xFFC54B8C) },
            { "Wisteria", new SKColor(0xFF997A8D) },
            { "Amethyst", new SKColor(0xFF9966CC) },
            { "ByzantinePurple", new SKColor(0xFFBD33A4) },
            { "Byzantium", new SKColor(0xFF702963) },
            { "Eggplant", new SKColor(0xFF614051) },
            { "Fandango", new SKColor(0xFFB53389) },
            { "Finn", new SKColor(0xFF683068) },
            { "Flirt", new SKColor(0xFFA2006D) },
            { "Fuchsia", SKColors.Fuchsia },
            { "Heliotrope", new SKColor(0xFFDF73FF) },
            { "Hibiscus", new SKColor(0xFFB86391) },
            { "Jazzberry", new SKColor(0xFFA50B5E) },
            { "Lavender", SKColors.Lavender },
            { "Lilac", new SKColor(0xFFC8A2C8) },
            { "Magenta", SKColors.Magenta },
            { "Mauve", new SKColor(0xFFE0B0FF) },
            { "MediumPurpleSK", new SKColor(0xFF9370DB) },
            { "Mountbatten", new SKColor(0xFF997A8D) },
            { "Pomp", new SKColor(0xFF7B4259) },
            { "Phlox", new SKColor(0xFFDF00FF) },
            { "Purpureus", new SKColor(0xFF9A4EAE) },
            { "RoyalPurpleSK", new SKColor(0xFF7851A9) },
            { "Tyrian", new SKColor(0xFF66023C) },
            { "VioletEggplant", new SKColor(0xFF991199) },

            // Shades of yellow and orange
            { "Gold", SKColors.Gold },
            { "DarkOrange", SKColors.DarkOrange },
            { "Goldenrod", SKColors.Goldenrod },
            { "DarkGoldenrod", SKColors.DarkGoldenrod },
            { "LightGoldenrodYellow", SKColors.LightGoldenrodYellow },
            { "PaleGoldenrod", SKColors.PaleGoldenrod },
            { "Khaki", SKColors.Khaki },
            { "DarkKhaki", SKColors.DarkKhaki },
            { "LemonChiffon", SKColors.LemonChiffon },
            { "LightYellow", SKColors.LightYellow },
            { "PapayaWhip", SKColors.PapayaWhip },
            { "Moccasin", SKColors.Moccasin },
            { "PeachPuff", SKColors.PeachPuff },
            { "Butter", new SKColor(0xFFFFE135) },
            { "Canary", new SKColor(0xFFFFFF99) },
            { "Apricot", new SKColor(0xFFFBCEB1) },
            { "Mandarin", new SKColor(0xFFF37A48) },
            { "Honey", new SKColor(0xFFA66F00) },
            { "Amber", new SKColor(0xFFFFBF00) },
            { "Aureolin", new SKColor(0xFFFDEE00) },
            { "BananaMania", new SKColor(0xFFFAE7B5) },
            { "Beer", new SKColor(0xFFFC913A) },
            { "Buff", new SKColor(0xFFF0DC82) },
            { "Butterscotch", new SKColor(0xFFFC9D03) },
            { "Caramel", new SKColor(0xFFFFD59A) },
            { "Champagne", new SKColor(0xFFF7E7CE) },
            { "Corn", new SKColor(0xFFFBEC5D) },
            { "Cream", new SKColor(0xFFFFFFCC) },
            { "Dandelion", new SKColor(0xFFF0E130) },
            { "GoldenYellow", new SKColor(0xFFFFDF00) },
            { "Jasmine", new SKColor(0xFFF8DE7E) },
            { "Lemon", new SKColor(0xFFFFF700) },
            { "Maize", new SKColor(0xFFE4B018) },
            { "Mustard", new SKColor(0xFFE1AD01) },
            { "Rajah", new SKColor(0xFFFBAB60) },
            { "Saffron", new SKColor(0xFFF4C430) },
            { "Sunglow", new SKColor(0xFFFFCC33) },
            { "Sunset", new SKColor(0xFFFAD6A5) },
            { "TigersEye", new SKColor(0xFFE08D3C) },
            { "Urobilin", new SKColor(0xFFE1C43F) },
            { "Bronze", new SKColor(0xFFCD7F32) },
            { "BurntOrange", new SKColor(0xFFCC5500) },
            { "Cider", new SKColor(0xFFF78700) },
            { "Copper", new SKColor(0xFFB87333) },
            { "InternationalOrange", new SKColor(0xFFFF4F00) },
            { "Persimmon", new SKColor(0xFFCC6500) },
            { "PrincetonOrange", new SKColor(0xFFF58025) },
            { "Pumpkin", new SKColor(0xFFFF7518) },
            { "TangoPink", new SKColor(0xFFE4717A) },
            { "TerraCotta", new SKColor(0xFFE2725B) },
            { "Vermilion", new SKColor(0xFFFF4000) },

            // Shades of brown
            { "SandyBrown", SKColors.SandyBrown },
            { "RosyBrown", SKColors.RosyBrown },
            { "SaddleBrown", SKColors.SaddleBrown },
            { "Chocolate", SKColors.Chocolate },
            { "Peru", SKColors.Peru },
            { "Sienna", SKColors.Sienna },
            { "BurlyWood", SKColors.BurlyWood },
            { "Tan", SKColors.Tan },
            { "Wheat", SKColors.Wheat },
            { "NavajoWhite", SKColors.NavajoWhite },
            { "Bisque", SKColors.Bisque },
            { "BlanchedAlmond", SKColors.BlanchedAlmond },
            { "Cornsilk", SKColors.Cornsilk },
            { "Mocha", new SKColor(0xFF967117) },
            { "Cinnamon", new SKColor(0xFFD2691E) },
            { "Taupe", new SKColor(0xFF483C32) },
            { "Umber", new SKColor(0xFF635147) },
            { "Auburn", new SKColor(0xFF922724) },
            { "Beaver", new SKColor(0xFF9F8170) },
            { "Beige", SKColors.Beige },
            { "Bole", new SKColor(0xFF79443B) },
            { "BuffBrown", new SKColor(0xFFE0AB76) },
            { "BurntUmbra", new SKColor(0xFF8A3324) },
            { "Cafe", new SKColor(0xFF4B3621) },
            { "Camel", new SKColor(0xFFC19A6B) },
            { "Chamoisee", new SKColor(0xFF9A784F) },
            { "Chestnut", new SKColor(0xFF954535) },
            { "CoffeeBrown", new SKColor(0xFF4A2C2A) },
            { "CoralBrown", new SKColor(0xFF5B3A29) },
            { "Cordovan", new SKColor(0xFF893F45) },
            { "Cork", new SKColor(0xFF583539) },
            { "Desert", new SKColor(0xFFEDC9AF) },
            { "Dun", new SKColor(0xFFC19A6B) },
            { "Ecru", new SKColor(0xFFC2B280) },
            { "Fallow", new SKColor(0xFFC19A6B) },
            { "Fawn", new SKColor(0xFFE5AA70) },
            { "KhakiBrown", new SKColor(0xFFC3B091) },
            { "Lion", new SKColor(0xFFC19A6B) },
            { "Liver", new SKColor(0xFF674C47) },
            { "Mahogany", new SKColor(0xFFC04000) },
            { "Ochre", new SKColor(0xFFCC7722) },
            { "Russet", new SKColor(0xFF8D4E85) },
            { "RustBrown", new SKColor(0xFFB7410E) },
            { "Sand", new SKColor(0xFFC2B280) },
            { "Sinopia", new SKColor(0xFFCB410B) },
            { "Walnut", new SKColor(0xFF773F1A) },
            { "Wood", new SKColor(0xFF823A09) },

            // Shades of pink
            { "PaleVioletRed", SKColors.PaleVioletRed },
            { "HotPink", SKColors.HotPink },
            { "DeepPink", SKColors.DeepPink },
            { "LightPink", SKColors.LightPink },
            { "MistyRose", SKColors.MistyRose },
            { "LavenderBlush", SKColors.LavenderBlush },
            { "Bubblegum", new SKColor(0xFFFFC1CC) },
            { "Flamingo", new SKColor(0xFFFC8EAC) },
            { "Blush", new SKColor(0xFFDE5D83) },
            { "CherryBlossom", new SKColor(0xFFFFB7C5) },
            { "Amaranth", new SKColor(0xFFE52B50) },
            { "Baker", new SKColor(0xFFFF5F65) },
            { "Begonia", new SKColor(0xFFFB607F) },
            { "Brink", new SKColor(0xFFFB607F) },
            { "BrinkPink", new SKColor(0xFFD88CA6) },
            { "Carnation", new SKColor(0xFFFFA6C9) },
            { "Cerise", new SKColor(0xFFDE3163) },
            { "Charm", new SKColor(0xFFE68FAC) },
            { "ChineseViolet", new SKColor(0xFF856088) },
            { "CoralPink", new SKColor(0xFFFF7F50) },
            { "Cyclamen", new SKColor(0xFFF4BBD3) },
            { "FrenchPink", new SKColor(0xFFFD6C9E) },
            { "LavenderPink", new SKColor(0xFFB57EDC) },
            { "MexicanPink", new SKColor(0xFFE4007C) },
            { "MountainPink", new SKColor(0xFFD58E94) },
            { "MulberryPink", new SKColor(0xFFC8509B) },
            { "PaleChestnut", new SKColor(0xFFDDACBF) },
            { "PearlPink", new SKColor(0xFFEA8BA0) },
            { "PersianPink", new SKColor(0xFFF77FBE) },
            { "PersianRose", new SKColor(0xFFFE28A2) },
            { "PiggyPink", new SKColor(0xFFFDDDE6) },
            { "PinkLace", new SKColor(0xFFFFDDF4) },
            { "PinkLavender", new SKColor(0xFFD8B2D1) },
            { "PinkPearl", new SKColor(0xFFE7ACCF) },
            { "RosyPink", new SKColor(0xFFFF66CC) },
            { "Rosewood", new SKColor(0xFF65000B) },
            { "RubineRed", new SKColor(0xFFD10056) },
            { "TeaRose", new SKColor(0xFFF4C2C2) },
            { "ThulianPink", new SKColor(0xFFDE6FA1) },

            // Shades of gray
            { "Silver", SKColors.Silver },
            { "DimGray", SKColors.DimGray },
            { "LightSlateGray", SKColors.LightSlateGray },
            { "DarkSlateGray", SKColors.DarkSlateGray },
            { "Gainsboro", SKColors.Gainsboro },
            { "LightGray", SKColors.LightGray },
            { "DarkGray", SKColors.DarkGray },
            { "SlateGray", SKColors.SlateGray },
            { "LightSteelBlue", SKColors.LightSteelBlue },
            { "Ash", new SKColor(0xFFB2BEB5) },
            { "Pewter", new SKColor(0xFF96A8A1) },
            { "Smoke", new SKColor(0xFF738276) },
            { "Granite", new SKColor(0xFF676767) },
            { "AshGray", new SKColor(0xFFB2BEB5) },
            { "BattleshipGray", new SKColor(0xFF848482) },
            { "Cadet", new SKColor(0xFF91A3B0) },
            { "Charcoal", new SKColor(0xFF36454F) },
            { "Cinerous", new SKColor(0xFF98817B) },
            { "Davy", new SKColor(0xFF555555) },
            { "Ebony", new SKColor(0xFF555D50) },
            { "GlaucousGray", new SKColor(0xFF6082B6) },
            { "Gunmetal", new SKColor(0xFF2A3439) },
            { "Jet", new SKColor(0xFF343434) },
            { "Onyx", new SKColor(0xFF0F0F0F) },
            { "Oyster", new SKColor(0xFFE6D5D1) },
            { "Payne", new SKColor(0xFF536878) },
            { "Platinum", new SKColor(0xFFE5E4E2) },
            { "Rocket", new SKColor(0xFF8A7F8D) },
            { "Slate", new SKColor(0xFF708090) },
            { "Stone", new SKColor(0xFF928E85) },
            { "Timberwolf", new SKColor(0xFFDBD7D2) },

            // Special and metallic colors
            { "Ivory", SKColors.Ivory },
            { "MintCream", SKColors.MintCream },
            { "Azure", SKColors.Azure },
            { "AliceBlue", SKColors.AliceBlue },
            { "AntiqueWhite", SKColors.AntiqueWhite },
            { "Aqua", SKColors.Aqua },
            { "Chartreuse", SKColors.Chartreuse },
            { "DarkCyan", SKColors.DarkCyan },
            { "FloralWhite", SKColors.FloralWhite },
            { "GhostWhite", SKColors.GhostWhite },
            { "Honeydew", SKColors.Honeydew },
            { "Linen", SKColors.Linen },
            { "MediumAquamarine", SKColors.MediumAquamarine },
            { "MediumTurquoise", SKColors.MediumTurquoise },
            { "OldLace", SKColors.OldLace },
            { "PaleTurquoise", SKColors.PaleTurquoise },
            { "Snow", SKColors.Snow },
            { "Turquoise", SKColors.Turquoise },
            { "WhiteSmoke", SKColors.WhiteSmoke },
            { "CopperMetallic", new SKColor(0xFFB87333) },
            { "Brass", new SKColor(0xFFB5A642) },
            { "Steel", new SKColor(0xFF4682B4) },
            { "AntiqueBrass", new SKColor(0xFFCD9575) },
            { "BronzeMetallic", new SKColor(0xFF8C7853) },
            { "ChromeGold", new SKColor(0xFFFFCF40) },
            { "ChromeSilver", new SKColor(0xFFDDDDDD) },
            { "CopperRed", new SKColor(0xFFCB6D51) },
            { "GoldMetallic", new SKColor(0xFFD4AF37) },
            { "Mercury", new SKColor(0xFFE6E6E6) },
            { "MetallicGold", new SKColor(0xFFD5A03C) },
            { "MetallicSunburst", new SKColor(0xFF9C7C38) },
            { "MetallicSunrise", new SKColor(0xFF817A70) },
            { "OldGold", new SKColor(0xFFCFB53B) },
            { "RoseGold", new SKColor(0xFFB76E79) },
            { "SilverMetallic", new SKColor(0xFFC0C0C0) },
            { "TitaniumGold", new SKColor(0xFFEEA319) },
            { "TitaniumWhite", new SKColor(0xFFF5F5F5) },

            // Additional custom colors
            { "LightPurple", new SKColor(0xFFDDA0DD) },
            { "Emerald", new SKColor(0xFF50C878) },
            { "Ruby", new SKColor(0xFFE0115F) },
            { "Sapphire", new SKColor(0xFF0F52BA) },
            { "JetBlack", new SKColor(0xFF0A0A0A) },
            { "Opal", new SKColor(0xFFA8C3BC) },
            { "Garnet", new SKColor(0xFF733635) },
            { "TurquoiseBlue", new SKColor(0xFF00CED1) },
            { "Sepia", new SKColor(0xFF704214) },
            { "Tangerine", new SKColor(0xFFF28500) },
            { "Verdant", new SKColor(0xFF4CAF50) },
            { "Scarlet", new SKColor(0xFFFF2400) },
            { "ElectricBlue", new SKColor(0xFF7DF9FF) },
            { "IceBlue", new SKColor(0xFF99FFFF) },
            { "MagentaPink", new SKColor(0xFFCC338B) },
            { "PeacockBlue", new SKColor(0xFF33A1C9) },
            { "PumpkinCustom", new SKColor(0xFFFF7518) },
            { "Seafoam", new SKColor(0xFF93E9BE) },
            { "Sunflower", new SKColor(0xFFFFDA03) },
            { "TealBlue", new SKColor(0xFF367588) },
            { "UltramarineBlue", new SKColor(0xFF3F00FF) },
            { "VermilionCustom", new SKColor(0xFFE34234) },
            { "Wine", new SKColor(0xFF722F37) },
            { "Zomp", new SKColor(0xFF39A78E) },
            { "Celadon", new SKColor(0xFFACE1AF) },
            { "DustyRose", new SKColor(0xFFDCAE96) },
            { "FawnBrown", new SKColor(0xFFE5AA70) },
            { "IndigoBlue", new SKColor(0xFF4B0082) },
            { "Lapis", new SKColor(0xFF26619C) },
            { "Raven", new SKColor(0xFF757575) },
            { "SageGreen", new SKColor(0xFF9BAA8D) },
            { "Twilight", new SKColor(0xFF4A4066) },

            // Gem colors
            { "Alexandrite", new SKColor(0xFF7FFFD4) },
            { "Amazonite", new SKColor(0xFF00DFBB) },
            { "Aventurine", new SKColor(0xFF84C3BE) },
            { "Beryl", new SKColor(0xFFDAA520) },
            { "Bloodstone", new SKColor(0xFF800020) },
            { "Calcite", new SKColor(0xFFE9E5CE) },
            { "Carnelian", new SKColor(0xFFB31B1B) },
            { "Citrine", new SKColor(0xFFE4D00A) },
            { "Diamond", new SKColor(0xFFB9F2FF) },
            { "Fluorite", new SKColor(0xFF7A89B8) },
            { "Iolite", new SKColor(0xFF3A3A78) },
            { "JadeGem", new SKColor(0xFF00A36C) },
            { "Jasper", new SKColor(0xFFD73B3E) },
            { "Kunzite", new SKColor(0xFFD47FFF) },
            { "Kyanite", new SKColor(0xFF5E91D4) },
            { "Labradorite", new SKColor(0xFF7B8282) },
            { "Morganite", new SKColor(0xFFCCCCFF) },
            { "Obsidian", new SKColor(0xFF000000) },
            { "Peridot", new SKColor(0xFF9BC256) },
            { "Quartz", new SKColor(0xFFEDEAE0) },
            { "Rhodonite", new SKColor(0xFFE73895) },
            { "RoseQuartz", new SKColor(0xFFFF91A4) },
            { "Sphene", new SKColor(0xFFC3B091) },
            { "Spinel", new SKColor(0xFFFF5A5F) },
            { "Sunstone", new SKColor(0xFFDD985C) },
            { "Tiger", new SKColor(0xFFE08D3C) },
            { "Tanzanite", new SKColor(0xFF4D5A9E) },
            { "TopazGem", new SKColor(0xFFFFC87C) },
            { "Tourmaline", new SKColor(0xFF85461E) },
            { "TurquoiseGem", new SKColor(0xFF30D5C8) },
            { "Zircon", new SKColor(0xFFADE6C4) },

            // Neon and vibrant colors
            { "NeonBlue", new SKColor(0xFF4D4DFF) },
            { "NeonGreen", new SKColor(0xFF39FF14) },
            { "NeonOrange", new SKColor(0xFFFF5F1F) },
            { "NeonPink", new SKColor(0xFFFF44CC) },
            { "NeonPurple", new SKColor(0xFFBF00FF) },
            { "NeonRed", new SKColor(0xFFFF3131) },
            { "NeonYellow", new SKColor(0xFFFF00) },
            { "AcidGreen", new SKColor(0xFFB0BF1A) },
            { "ElectricIndigo", new SKColor(0xFF6F00FF) },
            { "ElectricLime", new SKColor(0xFFCCFF00) },
            { "ElectricPurple", new SKColor(0xFFBF00FF) },
            { "ElectricViolet", new SKColor(0xFF8F00FF) },
            { "FluorescentOrange", new SKColor(0xFFFFBF00) },
            { "FluorescentPink", new SKColor(0xFFFF1493) },
            { "FluorescentYellow", new SKColor(0xFFCCFF00) },
            { "LaserLemon", new SKColor(0xFFFEFE22) },
            { "PsychedelicPurple", new SKColor(0xFFDF00FF) },
            { "ShockingPink", new SKColor(0xFFFC0FC0) },
            { "UltraViolet", new SKColor(0xFF5F00BA) },

            // Pastel colors
            { "PastelBlue", new SKColor(0xFFAEC6CF) },
            { "PastelBrown", new SKColor(0xFF836953) },
            { "PastelGray", new SKColor(0xFFCFCFC4) },
            { "PastelGreen", new SKColor(0xFF77DD77) },
            { "PastelMagenta", new SKColor(0xFFF49AC2) },
            { "PastelOrange", new SKColor(0xFFFFB347) },
            { "PastelPink", new SKColor(0xFFDEA5A4) },
            { "PastelPurple", new SKColor(0xFFB39EB5) },
            { "PastelRed", new SKColor(0xFFFF6961) },
            { "PastelViolet", new SKColor(0xFFCB99C9) },
            { "PastelYellow", new SKColor(0xFFFFFF9E) },
            { "BabyPink", new SKColor(0xFFF4C2C2) },
            { "ButtermilkYellow", new SKColor(0xFFF3F4C0) },
            { "CelestialBlue", new SKColor(0xFF4997D0) },
            { "DuckyYellow", new SKColor(0xFFFFDB58) },
            { "FreshGreen", new SKColor(0xFFB5D8CC) },
            { "MellowApricot", new SKColor(0xFFF8B878) },
            { "MintGreen", new SKColor(0xFF98FB98) },
            { "PastelRosyPink", new SKColor(0xFFFF66CC) },
            { "SalmonPink", new SKColor(0xFFFF91A4) },
            { "SandyBeige", new SKColor(0xFFF5DEB3) },
            { "SeafoamGreen", new SKColor(0xFF71EEB8) },
            { "SoftLilac", new SKColor(0xFFE6CFE6) }
        };
}